void _puts_recursion(char *s);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
void _putchar(char c);
int _strlen(char *str);
char *move_past_star(char *s2);
int inception(char *s1, char *s2);
int _strlen(char *s);
int do_is_palindrome(char *s, int l, int i);
int do_is_prime_number(int n, int m);
int do_sqrt_recursion(int n, int r);
